version: "3.8"

services:
  ffmpeg:
    platform: linux/arm64  # Ensure compatibility with your architecture
    image: ubuntu:20.04  # Lightweight Ubuntu version
    container_name: ffmpeg-stream
    restart: unless-stopped
    volumes:
      - ./hls:/app  # Ensure this directory exists with correct permissions
    command: >
      bash -c "
      apt update && apt install -y ffmpeg &&
      ffmpeg -rtsp_transport tcp 
      -i 'rtsp://jugal:jugal@192.0.0.4:8080/h264_opus.sdp' 
      -c:v copy -c:a copy 
      -hls_time 2 -hls_list_size 10 -hls_flags delete_segments 
      -start_number 1 /app/output.m3u8
      "
